version: 2

python:
  install:
    - requirements: bindings-python/vidyut/docs/requirements.txt
    - method: pip
      path: ./bindings-python

sphinx:
  builder: html
  configuration: bindings-python/vidyut/docs/source/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
    # Use a recent Rust to avoid weird build errors.
    rust: "1.82"
