version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
    # Use 1.64 since it supports Rust edition 2021 and clap_derive 4.1.0
    rust: "1.64"

python:
  install:
    - method: pip
      path: .
