[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "vidyut>=0.3.1",
]

[dependency-groups]
dev = [
    "ruff>=0.9.1",
]
